theme: jekyll-theme-cayman
title: An Athiest's Guide to Living Ethically
Description: Whilst we have the law as a directive for cilvilised living. There appears to be no code that acts of the guide to life in the modern world. I commonly hear the statement that religion provides moral guidance. I believe this may be true but I seek to create a document from all people aroudn the world that establishes the foundation for moral and ethical living in the modern world.
